@shadertype include
@namespace oversized_screen_triangle

@exportfunc
vec4 calcOversizedScreenTriangleCoord(int vertexID, out vec2 screenTexCoord) {
//	vec2 xy = -1.0 + vec2(float((vertexID & 1) << 2), float((vertexID & 2) << 1));
//	screenTexCoord = xy * 0.5 + 0.5;
//	return vec4(xy, 0.0, 1.0);
	
	vec2 xy = -1.0 + vec2((ivec2(vertexID) & ivec2(1, 2)) << ivec2(2, 1));
	screenTexCoord = xy * 0.5 + 0.5;
	return vec4(xy, 0.0, 1.0);
}
@end
